# Generated by Django 4.0.3 on 2022-03-20 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recomendaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documentales',
            new_name='Documental',
        ),
        migrations.RenameModel(
            old_name='Peliculas',
            new_name='Pelicula',
        ),
        migrations.RenameModel(
            old_name='Series',
            new_name='Serie',
        ),
    ]
