# Generated by Django 4.0.3 on 2022-04-10 19:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recomendaciones', '0004_series_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
