# Generated by Django 4.0.3 on 2022-04-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendaciones', '0005_alter_series_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='descripcion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
