# Generated by Django 4.0.3 on 2022-04-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendaciones', '0006_alter_series_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
