# Generated by Django 4.0.3 on 2022-04-15 20:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recomendaciones', '0008_delete_documentales_peliculas_author_series_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
