# Generated by Django 4.0.3 on 2022-04-15 20:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recomendaciones', '0009_peliculas_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
