# Generated by Django 4.0.3 on 2022-04-16 19:28

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recomendaciones', '0011_alter_series_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='series',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
